//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class hoteles
{
    public int id_ciudad { get; set; }
    public string nombre { get; set; }
    public int categoria { get; set; }
    public string direccion { get; set; }
    public int telefono { get; set; }
    public string tipo { get; set; }
    public string cif { get; set; }

    public virtual cadenas cadenas { get; set; }
    public virtual ciudades ciudades { get; set; }
}
